name: nepali_english_calendar
description: Nepali Calendar with the custom styles and colors.
version: 1.0.0
homepage: https://github.com/lakshydeep-14/nepali_english_calendar

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.3
  flutter_layout_grid: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
